FROM grpc/python

WORKDIR /client

COPY requirements.txt /client/requirements.txt

RUN pip install --upgrade pip

# Cache the dependencies
RUN pip install -r /client/requirements.txt

# Copy the sources, including the stubs
COPY client.py /client/client.py
# COPY kv /client/kv

RUN chmod a+x /client/client.py

# http://bigdatums.net/2017/11/07/how-to-keep-docker-containers-running/
# Call docker exec /client/grpc.py set | get
CMD tail -f /dev/null
